core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from memoria import views as memoria_views # Import the views from memoria

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', memoria_views.home, name='home'),  # Set the home view as the default
    path('memoria/', include('memoria.urls', namespace='memoria')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('carousel/', include('carousel.urls', namespace='carousel')),
    path('qr/', include('qr.urls', namespace='qr')),
    path('<str:hash>/', memoria_views.hash_redirect, name='hash_redirect'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memoria/urls.py
from django.urls import path
from . import views

app_name = 'memoria'  # Add this line

urlpatterns = [
    path('', views.home, name='home'),
    path('quienes_somos/', views.quienes_somos, name='quienes_somos'),
    path('planes/', views.planes, name='planes'),
    path('galeria/', views.galeria, name='galeria'),
    path('contacto/', views.contacto, name='contacto'),
    path('dashboard_home/', views.dashboard_home, name='dashboard_home'),
    path('dashboard_familiarRegistro/', views.familiarRegistro, name='dashboard_familiarRegistro'),
    path('dashboard_familiarListado/', views.familiarListado, name='dashboard_familiarListado'),
    path('familiarDelete/<int:familiar_id>/', views.familiarDelete, name='familiarDelete'),
    path('dashboard_familiarUpdate/<int:familiar_id>/', views.familiarUpdate, name='dashboard_familiarUpdate'),
    path('userLogin/', views.userLogin, name='userLogin'),
    path('userLogout/', views.userLogout, name='userLogout'),
    path('userRegistro/', views.userRegistro, name='userRegistro'),
    path('activar-cuenta/<int:user_id>/', views.activar_cuenta, name='activar_cuenta'),
    path('cambiaPass/', views.CustomChangePasswordView.as_view(), name='cambiaPass'),
    path('cambiaPass/logout/', views.userLogout, name='cambiaPass/logout'),
    path('perfil/', views.user_profile, name='perfil'),
    path('dashboard_suscripcion/', views.dashboard_suscripcion, name='dashboard_suscripcion'),
    path('pagoexitoso/', views.pago_exitoso, name='pagoexitoso'),
    path('queplan/', views.queplan, name='queplan'),
]

qr/urls.py
from django.urls import path
from . import views

app_name = 'qr'

urlpatterns = [
    path('', views.generar_qr, name='generar_qr'),
]

memoria/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxLengthValidator
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from datetime import date
import random
import string
import os

class Memorial(models.Model):
    id_memorial=models.AutoField(primary_key=True)
    nombre=models.CharField(max_length=250)
    class Meta:
        verbose_name = ("Memorial")
        verbose_name_plural = ("Memorials")

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse("Memorial_detail", kwargs={"pk": self.pk})

class Planes(models.Model):
    id_plan=models.AutoField(primary_key=True)
    nombre=models.CharField(max_length=50)
    descripcion=models.TextField()
    cantidad = models.IntegerField()
    valor_factor = models.IntegerField()
    link_pago=models.CharField(max_length=50)
    class Meta:
        verbose_name = ("Planes")
        verbose_name_plural = ("Planes")

    def __str__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse("Planes_detail", kwargs={"pk": self.pk})

class Familiares(models.Model):
    OPC_NACIONALIDAD = (
        ('AR', 'Argentina'),
        ('BO', 'Bolivia'),
        ('BR', 'Brasil'),
        ('CL', 'Chile'),
        ('CO', 'Colombia'),
        ('CR', 'Costa Rica'),
        ('CU', 'Cuba'),
        ('EC', 'Ecuador'),
        ('SV', 'El Salvador'),
        ('GT', 'Guatemala'),
        ('HN', 'Honduras'),
        ('MX', 'México'),
        ('NI', 'Nicaragua'),
        ('PA', 'Panamá'),
        ('PY', 'Paraguay'),
        ('PE', 'Perú'),
        ('PR', 'Puerto Rico'),
        ('DO', 'República Dominicana'),
        ('UY', 'Uruguay'),
        ('VE', 'Venezuela'),
        ('OT','Otra')
    )

    id_familiar = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    nombre_familiar = models.CharField(max_length=100)
    apellidos_familiar = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField(auto_now=False, auto_now_add=False)
    fecha_deceso = models.DateField(auto_now=False, auto_now_add=False)
    parentezco = models.CharField(max_length=100)
    nacionalidad = models.CharField(max_length=2, choices=OPC_NACIONALIDAD, default='CL')
    avatar_picture = models.ImageField(upload_to='familiares_images/', null=True, blank=True)
    unique_hash = models.CharField(max_length=10, unique=True, blank=True, null=True)
    visitas = models.PositiveIntegerField(default=0) 

    def __str__(self):
        return f"{self.nombre_familiar} {self.apellidos_familiar}"

    def save(self, *args, **kwargs):
        if not self.unique_hash:
            self.unique_hash = self.generate_unique_hash()
        super().save(*args, **kwargs)

    def generate_unique_hash(self):
        hash = ''.join(random.choices(string.ascii_letters + string.digits, k=10))
        while Familiares.objects.filter(unique_hash=hash).exists():
            hash = ''.join(random.choices(string.ascii_letters + string.digits, k=10))
        return hash

class AdditionalImage(models.Model):
    image = models.ImageField(upload_to='additional_images/')
    familiar = models.ForeignKey(Familiares, on_delete=models.CASCADE, related_name='additional_images')

    def __str__(self):
        return f"Additional Image for {self.familiar.nombre_familiar}"

class Roles(models.Model):
    id_rol=models.AutoField(primary_key=True)
    nombre_rol=models.CharField(max_length=100)

    def __str__(self):
        return self.nombre_rol

class Recuerdos(models.Model):
    id_recuerdo=models.AutoField(primary_key=True)
    nombre_recuerdo=models.CharField(max_length=100, default='Nombre Recuerdo')
    descripcion_recuerdo=models.TextField()

    def __str__(self):
        return self.nombre_recuerdo

class Usuarios(models.Model):
    id_usuario=models.AutoField(primary_key=True)
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    email=models.EmailField()
    contraseña = models.CharField(max_length=128)
    rol = models.ForeignKey(Roles, on_delete=models.CASCADE)
    
    def set_password(self, raw_password):
        self.contraseña = make_password(raw_password)

    def __str__(self):
        return f"{self.nombres} {self.apellidos}"

class Usuarios_Planes(models.Model):
    id_plan_usuario=models.AutoField(primary_key=True)
    id_plan=models.ForeignKey(Planes, on_delete=models.CASCADE)
    id_usuario=models.ForeignKey(User, on_delete=models.CASCADE)
    estado=models.IntegerField(default=0)
    fecha_act=models.DateField(auto_now_add=False, default=date.today)

    def __str__(self):
        return f"Usuario: {self.id_usuario.username} - Plan: {self.id_plan.nombre} - Estado: {self.estado}"

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    familiar = models.ForeignKey(Familiares, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    image_url = models.URLField(max_length=200, blank=True, null=True)

    def __str__(self):
        return f"Comment by {self.user.username} on {self.familiar.nombre_familiar}"

memoria/views.py
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash, get_user_model
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.core.mail import send_mail
from django.urls import reverse_lazy
from .models import Memorial, Planes, Usuarios_Planes, Familiares
import requests
import os
from .forms import formUserRegistro, formFamiliarRegistro, formFamiliarUpdate, CustomChangePasswordForm, UserProfileForm, SuscripcionForm

def hash_redirect(request, hash):
    try:
        # Buscar el familiar correspondiente al hash
        familiar = get_object_or_404(Familiares, unique_hash=hash)
        
        # Incrementar el contador de visitas
        familiar.visitas += 1
        familiar.save()

        # Construir la URL completa para la redirección
        redirect_url = f"{settings.SITE_URL}/carousel/{familiar.id_familiar}/"
        
        # Redirigir a la URL específica del familiar
        return redirect(redirect_url)
    except Http404:
        # Devolver una respuesta con un script para mostrar un mensaje de alerta y redirigir
        message = "El memorial solicitado, no existe en nuestra base de datos, o corresponde a un memorial privado."
        script = f"""
        <script type="text/javascript">
            alert("{message}");
            window.location.href = "{settings.SITE_URL}/";
        </script>
        """
        return HttpResponse(script)


def home(request):

    return render(request, "memoria/home.html")

def quienes_somos(request):
    return render(request, "memoria/quienes_somos.html")

def planes(request):
    listaPlanes=Planes.objects.all()

    url = 'https://mindicador.cl/api'
    response = requests.get(url)
    data = response.json()
    dolar_value = data['dolar']['valor']
    uf_value = data['uf']['valor']
    bitcoin_value = data['bitcoin']['valor']
    context = {
        "planes": listaPlanes,
        "dolar": dolar_value,
        "uf": uf_value,
        "bitcoin": bitcoin_value
    }
    
    
    return render(request, "memoria/planes.html", context)

def galeria(request):
    return render(request, "memoria/galeria.html")

def contacto(request):
    return render(request, "memoria/contacto.html")

def userLogin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('dashboard:dashboard_home')  # Use the dashboard namespace here
        else:
            messages.error(request, 'Contraseña incorrecta')
            return render(request, 'memoria/userLogin.html')
    else:
        return render(request, 'memoria/userLogin.html')


    
def userLogout(request):
    logout(request)
    return redirect("userLogin")   
    
@login_required
def dashboard_home(request):
    return render(request, 'memoria/dashboard_home.html')

def userRegistro(request):
    if request.method == 'POST':
        form = formUserRegistro(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            group = Group.objects.get(name='Clientes')  
            user.groups.add(group)
            
            activation_link = 'https://memor-ia.cl/memoria/activar-cuenta/' + str(user.id)
            imagen_url = request.build_absolute_uri('https://virtual.cl/img/logo1.png')
            contenido_html = f"""
                <html>
                <head></head>
                <body>
                    <img src="{imagen_url}" style="width:200px"><br>
                    <h2>Bienvenido a MemorIA</h2>
                    <h2>{user.username.upper()}</h2><h3>
                    <a href="{activation_link}">Haz clic aquí para activar tu cuenta</a></h3>
                </body>
                </html>
            """
            send_mail(
                'Activa tu cuenta',
                '',
                'noreply@tu-sitio.com',
                [user.email],
                fail_silently=False,
                html_message=contenido_html
            )
            messages.success(request, 'Registro exitoso. Se ha enviado un correo electrónico para activar tu cuenta.')
            return redirect('/')  
    else:
        form = formUserRegistro()
    return render(request, 'memoria/userRegistro.html', {'userRegistro': form})



User = get_user_model()
def activar_cuenta(request, user_id):
    try:
        user = User.objects.get(id=user_id, is_active=False)
        # Activa la cuenta del usuario
        user.is_active = True
        user.save()
        return render(request, 'memoria/cuenta_activada.html')
    except User.DoesNotExist:
        return render(request, 'memoria/error_activacion.html')
    

class CustomChangePasswordView(PasswordChangeView):
    form_class = CustomChangePasswordForm
    template_name = 'memoria/dashboard_pass.html'
    success_url = reverse_lazy('userLogout')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Contraseña cambiada correctamente.')
        logout(self.request)
        return response
    
@login_required
def user_profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('dashboard_home')
    else:
        form = UserProfileForm(instance=request.user)
    return render(request, 'memoria/dashboard_perfil.html', {'form': form})
    
@login_required
def dashboard_suscripcion(request):
    user = request.user
    
    url = 'https://mindicador.cl/api'
    response = requests.get(url)
    data = response.json()
    uf_value = data['uf']['valor']

    suscripcion_existente = Usuarios_Planes.objects.filter(id_usuario=user.id).first()

    if suscripcion_existente:

        form = SuscripcionForm(request.POST or None, initial={'plan': suscripcion_existente.id_plan})
        if request.method == 'POST':
            if form.is_valid():
                suscripcion_existente.id_plan = form.cleaned_data['plan']
                suscripcion_existente.save()
                return redirect('dashboard_suscripcion')
    else:

        form = SuscripcionForm(request.POST or None)
        if request.method == 'POST':
            if form.is_valid():
                plan = form.cleaned_data['plan']
                estado = 0
                Usuarios_Planes.objects.create(id_usuario=user, id_plan=plan, estado=estado)
                return redirect('dashboard_suscripcion')
    
    planes_asociados = Usuarios_Planes.objects.filter(id_usuario=user.id)
        
    context = {
        'form': form,
        'planes_asociados': planes_asociados,
        "uf": uf_value,
    }        

    return render(request, 'memoria/dashboard_suscripcion.html', context)

def familiarRegistro(request):
    if request.method == 'POST':
        form = formFamiliarRegistro(request.POST)
        if form.is_valid():
            names = form.cleaned_data['names']
            lastnames = form.cleaned_data['lastnames']
            date_of_birth = form.cleaned_data['date_of_birth']
            date_of_death = form.cleaned_data['date_of_death']
            relationship = form.cleaned_data['relationship']
            nationality = form.cleaned_data['nationality']
            if 'avatar_picture' in request.FILES:
                picture = request.FILES['avatar_picture']
                picture_path = os.path.join(settings.MEDIA_ROOT, picture.name)
                with open(picture_path, 'wb') as f:
                    for chunk in picture.chunks():
                        f.write(chunk)

            familiar = Familiares(
                nombre_familiar=names,
                apellidos_familiar=lastnames,
                fecha_nacimiento=date_of_birth,
                fecha_deceso=date_of_death,
                parentezco=relationship,
                nacionalidad=nationality,                
            )
            familiar.user_id=request.user.id
            familiar.save()
            #messages.success(request, 'Familiar creado exitosamente.')
            return redirect('dashboard_familiarListado')
            
            
    else:
        form = formFamiliarRegistro()
        form.fields['user_id'].initial = request.user.id
    
    context = {'form': form}
    return render(request, 'memoria/dashboard_familiarRegistro.html', context)

@login_required
def familiarListado(request):
    familiares = Familiares.objects.filter(user=request.user).order_by('-id_familiar')

def suscripcion(request):
    usuario = request.user
    suscripcion = Usuarios_Planes.objects.filter(id_usuario=usuario).first()
    context = {
        'suscripcion': suscripcion
    }
    return render(request, 'suscripcion.html', context)
    # Create a list of dictionaries containing the desired information
    familiares_data = []
    for familiar in familiares:
        data = {
            'id_familiar':familiar.id_familiar,
            'nombre_apellidos': f'{familiar.nombre_familiar} {familiar.apellidos_familiar}',
            'edad': familiar.fecha_deceso.year - familiar.fecha_nacimiento.year,
            'parentezco': familiar.parentezco,
            'fecha_deceso': familiar.fecha_deceso,
        }
        familiares_data.append(data)

    context = {
        'familiares': familiares_data,
    }
    return render(request, 'memoria/dashboard_familiarListado.html', context)

@login_required

templates/memoria/dashboard_pago.html
{% extends 'memoria/dashboard_base.html' %} 
{% load crispy_forms_tags %}
{% block content %}
<style>
    .abs-center {
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 40vh;
      }
      
    .mi_input{
        border:1px solid #red;
    }

</style>

<div class="container">
    <h1>Cambiar contraseña</h1>    
    <div class="abs-center">

pago exitoso, plan activado
          
    </div>
</div>

{% if error %}
    <p>{{ error }}</p>
{% endif %}

{% endblock %}

templates/memoria/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>memorIA</title>
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js" integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="{% static 'img/logo1.png' %}" width="70%" alt="Logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" style="font-size: 18px;{% if request.path == '/' %}font-weight: bold; color:#336699; {% endif %}"
                            href="{% url 'memoria:home' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="font-size: 18px; {% if request.path == '/quienes_somos/' %}font-weight: bold; color:#336699; {% endif %}" href="{% url 'memoria:quienes_somos' %}">Quienes
                            Somos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="font-size: 18px; {% if request.path == '/planes/' %}font-weight: bold; color:#336699; {% endif %}" href="{% url 'memoria:planes' %}">Planes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="font-size: 18px; {% if request.path == '/galeria/' %}font-weight: bold; color:#336699; {% endif %}" href="{% url 'memoria:galeria' %}">Galeria</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="font-size: 18px; {% if request.path == '/contacto/' %}font-weight: bold; color:#336699; {% endif %}" href="{% url 'memoria:contacto' %}">Contacto</a>
                    </li>
                </ul>
                <div class="d-flex">
                {% if user.is_authenticated %}                    
                    <a class="btn btn-outline-primary" style="font-size: 18px; {% if request.path == '/dashboard' %}font-weight: bold; color:#336699; {% endif %}" href="{% url 'dashboard:dashboard_home' %}">Bienvenido {{ request.user.username }}</a> &nbsp;<a class="btn btn-primary" style="font-size: 18px;" href="{% url 'dashboard:userLogout' %}">Salir</a> 
                {% else %}
                <a class="btn btn-primary" style="font-size: 18px;" href="{% url 'memoria:userLogin' %}">Ingresar</a>&nbsp;
                <a style="font-size: 18px;" href="{% url 'memoria:userRegistro' %}" class="btn btn-secondary">Registro</a>
                {% endif %}
                </div>
            </div>
        </div>
    </nav>

    <!-- Modal -->
    <div class="modal fade" id="modalLogin" tabindex="-1" aria-labelledby="modalLogin" aria-hidden="true">
        <div class="modal-dialog modal-md">
            <div class="modal-content modal-dialog-centered">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Ingreso al sistema</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <main class="form-signin w-100 m-auto mx-auto">
                        <form name="formLogin" action="{% url 'memoria:dashboard_home' %} id="formLogin" method="post">
                            {% csrf_token %}
                            <img class="mb-4" src="{% static 'img/logo1.png' %}" alt="" width="300" padding>
                            <div>
                                <input type="text" class="form-control" id="floatingPassword" name="username">
                            </div>
                            <div >
                                <input type="password" class="form-control" id="floatingPassword" name="password">
                            </div>
                            <button type="submit" id="botonLogin" class="btn btn-primary" data-bs-dismiss="modal">Ingresar</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                        </form>
                    </main>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal Registro -->
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>

    <div class="container">
        <div class="row">
          <div class="col-4 mx-auto">
            <p class="lead text-body-secondary">
              "Preservamos recuerdos con IA. Contáctanos para crear un memorial virtual personalizado y mantener vivo el legado de tus seres queridos."
            </p>
            <p>
          </div>

          <div class="col-2 mx-auto">
            <ul class="nav flex-column">
              <li class="nav-item mb-2"><a href="{% url 'memoria:home' %}" class="nav-link link-dark">Inicio</a></li>
              <li class="nav-item mb-2"><a href="{% url 'memoria:quienes_somos' %}" class="nav-link">Quienes Somos</a></li>
              <li class="nav-item mb-2"><a href="{% url 'memoria:planes' %}" class="nav-link">Planes</a></li>
              <li class="nav-item mb-2"><a href="{% url 'memoria:galeria' %}" class="nav-link">Galeria</a></li>
              <li class="nav-item mb-2"><a href="{% url 'memoria:contacto' %}" class="nav-link">Contactenos</a></li>
            </ul>
          </div>

          <div class="col-5">
            <form>
              <h5>Ten noticias nuestras</h5>
              <p>Dejanos tu correo y te enviaremos noticias de nuestros servicios.</p>
              <div class="d-flex flex-column flex-sm-row w-100 gap-2">
                <label for="newsletter1" class="visually-hidden">Email</label>
                <input id="newsletter1" type="text" class="form-control" placeholder="Correo Electronico">
                <button class="btn btn-primary" type="button">Suscribase</button>
              </div>
            </form>
          </div>
        </div>
    </div>

    <div class="container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            <div class="col-md-4 d-flex align-items-center">
                <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                    <svg class="bi" width="30" height="24">
                        <use xlink:href="#bootstrap"></use>
                    </svg>
                </a>
                <span class="mb-3 mb-md-0 text-body-secondary">© 2023 MemorIA SpA, Santiago - Chile</span>
            </div>

            <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                <li class="ms-3"><a class="text-body-secondary" href="#">Twitter</a></li>
                <li class="ms-3"><a class="text-body-secondary" href="#">Instagram</a></li>
            </ul>
        </footer>
    </div>
</body>
</html>

templates/memoria/userLogin.html
<!-- templates/memoria/userLogin.html -->
{% extends 'memoria/index.html' %}
{% load static %}
{% block content %}
<style>
    body {
        background-image: url("{% static 'img/cloudsbackground.png' %}");
        background-size: cover;
        background-repeat: no-repeat;
        background-position: center top;      
    }

    .abs-center {
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 80vh;
        background-color: rgba(255, 255, 255, 0.0);
        padding: 0px;
    }
    
    .form-container {
        background-color: rgba(255, 255, 255, 0.5);
        border-radius: 0px;
        padding: 60px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    
    .form-title {
        text-align: center;
        margin-bottom: 20px;
        font-size: 24px;
        color: #333;
    }
    
    .form-label {
        font-weight: bold;
        color: #333;
    }
    
    .form-control {
        margin-bottom: 10px;
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ccc;
        background-color: rgba(255, 255, 255, 0.9);
        width: 100%;
    }
    
    .form-control:focus {
        outline: none;
        box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);
        border-color: #007bff;
    }
    
    .btn-primary {
        background-color: #007bff;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
    }
    
    .btn-primary:hover {
        background-color: #0069d9;
    }
    
    .error-message {
        color: red;
        margin-top: 10px;
    }
</style>

<div class="abs-center">
    <div class="form-container">
        <h2 class="form-title">Ingreso de Usuarios</h2>
        <form method="POST" action="{% url 'memoria:userLogin' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="username" class="form-label">Nombre de Usuario</label>
                <input type="text" name="username" placeholder="Nombre de usuario" class="form-control" id="username">
            </div>
            <div class="form-group">
                <label for="password" class="form-label">Contraseña</label>
                <input type="password" name="password" placeholder="Contraseña" class="form-control" id="password">
            </div>
            <div class="col text-center" style="margin:8px;">    
                <input type="submit" value="Iniciar sesión" class="btn btn-primary center-block">
            </div>
        </form>                
    </div>
    {% if error %}
        <p class="error-message">{{ error }}</p>
    {% endif %}
</div>

{% endblock %}