carousel/urls.py
from django.urls import path
from . import views

app_name = 'carousel'

urlpatterns = [
    path('<int:pk>/', views.carousel_home, name='carousel_home'),
    path('add/', views.add_familiar, name='add_familiar'),
    path('edit/<int:pk>/', views.edit_familiar, name='edit_familiar'),
    path('remove/<int:pk>/', views.remove_familiar, name='remove_familiar'),
    path('comments/', views.post_comment, name='post_comment'),
    path('comments/fetch/', views.fetch_comments, name='fetch_comments'),
    path('upload_image/', views.upload_image, name='upload_image'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from memoria import views as memoria_views # Import the views from memoria

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', memoria_views.home, name='home'),  # Set the home view as the default
    path('memoria/', include('memoria.urls', namespace='memoria')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('carousel/', include('carousel.urls', namespace='carousel')),
    path('qr/', include('qr.urls', namespace='qr')),
    path('<str:hash>/', memoria_views.hash_redirect, name='hash_redirect'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
# dashboard/urls.py
from django.urls import path
from . import views
from .views import CustomChangePasswordView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard_home, name='dashboard_home'),
    path('list/', views.list_familiares, name='list_familiares'),
    path('add/', views.add_familiar, name='add_familiar'),
    path('update/<int:pk>/', views.update_familiar, name='update_familiar'),
    path('delete/<int:pk>/', views.delete_familiar, name='delete_familiar'),
    path('userLogout', views.userLogout, name='userLogout'),
    path('user_profile', views.user_profile, name='user_profile'),
    path('cambiaPass', CustomChangePasswordView.as_view(), name='cambiaPass'),    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

memoria/urls.py
from django.urls import path
from . import views

app_name = 'memoria'  # Add this line

urlpatterns = [
    path('', views.home, name='home'),
    path('quienes_somos/', views.quienes_somos, name='quienes_somos'),
    path('planes/', views.planes, name='planes'),
    path('galeria/', views.galeria, name='galeria'),
    path('contacto/', views.contacto, name='contacto'),
    path('dashboard_home/', views.dashboard_home, name='dashboard_home'),
    path('dashboard_familiarRegistro/', views.familiarRegistro, name='dashboard_familiarRegistro'),
    path('dashboard_familiarListado/', views.familiarListado, name='dashboard_familiarListado'),
    path('familiarDelete/<int:familiar_id>/', views.familiarDelete, name='familiarDelete'),
    path('dashboard_familiarUpdate/<int:familiar_id>/', views.familiarUpdate, name='dashboard_familiarUpdate'),
    path('userLogin/', views.userLogin, name='userLogin'),
    path('userLogout/', views.userLogout, name='userLogout'),
    path('userRegistro/', views.userRegistro, name='userRegistro'),
    path('activar-cuenta/<int:user_id>/', views.activar_cuenta, name='activar_cuenta'),
    path('cambiaPass/', views.CustomChangePasswordView.as_view(), name='cambiaPass'),
    path('cambiaPass/logout/', views.userLogout, name='cambiaPass/logout'),
    path('perfil/', views.user_profile, name='perfil'),
    path('dashboard_suscripcion/', views.dashboard_suscripcion, name='dashboard_suscripcion'),
    path('pagoexitoso/', views.pago_exitoso, name='pagoexitoso'),
    path('queplan/', views.queplan, name='queplan'),
]

qr/urls.py
from django.urls import path
from . import views

app_name = 'qr'

urlpatterns = [
    path('', views.generar_qr, name='generar_qr'),
]

dashboard/forms.py
from django import forms
from memoria.models import Familiares
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, UserChangeForm
from django.core.exceptions import ValidationError
from django.forms.widgets import DateInput
from django.forms import PasswordInput
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout
from django.contrib.auth import get_user_model

UserModel = get_user_model()

class FamiliaresForm(forms.ModelForm):
    class Meta:
        model = Familiares
        fields = ['nombre_familiar', 'apellidos_familiar', 'fecha_nacimiento', 'fecha_deceso', 'parentezco', 'nacionalidad', 'avatar_picture']
        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'fecha_deceso': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'nombre_familiar': forms.TextInput(attrs={'class': 'form-control'}),
            'apellidos_familiar': forms.TextInput(attrs={'class': 'form-control'}),
            'parentezco': forms.TextInput(attrs={'class': 'form-control'}),
            'nacionalidad': forms.Select(attrs={'class': 'form-control'}),
            'avatar_picture': forms.FileInput(attrs={'class': 'form-control'}),
        }


        
class UserProfileForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = PasswordInput(render_value=False)
    
        helper = FormHelper()
        helper.form_method = 'POST'
        helper.add_input(Submit('submit', 'Guardar perfil'))

    class Meta:
        model = UserModel
        fields = ['username','first_name', 'last_name']

class CustomChangePasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.add_input(Submit('submit', 'Cambiar Contraseña'))
   

dashboard/views.py
# dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import FamiliaresForm, UserProfileForm, CustomChangePasswordForm
from memoria.models import Familiares
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.views import PasswordChangeView
import qrcode
from django.conf import settings
import os  # Add the missing import for os


@login_required
def dashboard_home(request):
    familiares = Familiares.objects.filter(user=request.user)
    return render(request, 'dashboard/dashboard_home.html', {'familiares': familiares})

@login_required
def list_familiares(request):
    familiares = Familiares.objects.filter(user=request.user)
    context = {
        'familiares': familiares,
        'MEDIA_URL': settings.MEDIA_URL,
    }
    return render(request, 'dashboard/list_familiares.html', context)

def list_familiares(request):
    familiares = Familiares.objects.filter(user=request.user)
    return render(request, 'dashboard/list_familiares.html', {'familiares': familiares})

@login_required
def add_familiar(request):
    if request.method == 'POST':
        form = FamiliaresForm(request.POST, request.FILES)
        if form.is_valid():
            familiar = form.save(commit=False)
            familiar.user = request.user
            familiar.save()

            # Generar código QR
            qr_url = f"{settings.SITE_URL}/{familiar.unique_hash}"
            qr = qrcode.make(qr_url)
            qr_filename = os.path.join(settings.MEDIA_ROOT, 'qrcodes', f'{familiar.unique_hash}.png')
            os.makedirs(os.path.dirname(qr_filename), exist_ok=True)  # Ensure directory exists
            qr.save(qr_filename)

            return redirect('dashboard:list_familiares')
    else:
        form = FamiliaresForm()
    return render(request, 'dashboard/add_familiar.html', {'form': form})

@login_required
def update_familiar(request, pk):
    familiar = get_object_or_404(Familiares, pk=pk)
    if request.method == 'POST':
        form = FamiliaresForm(request.POST, request.FILES, instance=familiar)
        if form.is_valid():
            form.save()
            return redirect('dashboard:list_familiares')
    else:
        form = FamiliaresForm(instance=familiar)
    return render(request, 'dashboard/update_familiar.html', {'form': form})

@login_required
def delete_familiar(request, pk):
    familiar = get_object_or_404(Familiares, pk=pk)
    if request.method == 'POST':
        familiar.delete()
        return redirect('dashboard:list_familiares')
    return render(request, 'dashboard/delete_familiar.html', {'familiar': familiar})

def userLogout(request):
    logout(request)
    return redirect('/')   


@login_required
def user_profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = UserProfileForm(instance=request.user)
    return render(request, 'dashboard/user_profile.html', {'form': form})


class CustomChangePasswordView(PasswordChangeView):
    form_class = CustomChangePasswordForm
    template_name = 'dashboard/dashboard_pass.html'
    success_url = reverse_lazy('userLogout')
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, 'Contraseña cambiada correctamente.')
        logout(self.request)
        return response

templates/dashboard/add_familiar.html
{% extends 'dashboard/base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Agregar Familiar</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Agregar</button>
    </form>
</div>
{% endblock %}

templates/dashboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>memorIA</title>
   
        <script src="https://code.jquery.com/jquery-3.6.4.js"
            integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
        <script src="https://unpkg.com/@popperjs/core@2"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.min.js"
            integrity="sha384-heAjqF+bCxXpCWLa6Zhcp4fu20XoNIA98ecBC1YkdXhszjoejr5y9Q77hIrv8R9i"
            crossorigin="anonymous"></script>
            <link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %}">       
            <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>  
            <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels"></script>        
    </head>


    <body>
        <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
            <div class="container">
                <a class="navbar-brand" href="#">
                    <img src="{% static '/img/logo1.png' %}" width="70%" alt="Logo">
                </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:dashboard_home' %}">Inicio</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Perfil de Usuario
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'dashboard:user_profile' %}">Completar datos</a>
                        <a class="dropdown-item" href="{% url 'dashboard:cambiaPass' %}">Cambiar contraseña</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Gestionar Familiares
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'dashboard:add_familiar' %}">Añadir Familiar</a>
                        <a class="dropdown-item" href="{% url 'dashboard:list_familiares' %}">Ver Familiares</a>
                    </div>
                </li>                
            </ul>
        </div>
        <div class="d-flex">
            {% if user.is_authenticated %}                    
                <a class="btn btn-outline-primary" style="font-size: 18px; {% if request.path == '/dashboard' %}font-weight: bold; color:#336699; {% endif %}" href="{% url 'dashboard:dashboard_home' %}">Bienvenido {{ request.user.username }}</a> &nbsp;<a class="btn btn-primary" style="font-size: 18px;" href="{% url 'dashboard:userLogout' %}">Salir</a> 
            {% else %}
            <a class="btn btn-primary" style="font-size: 18px;" href="{% url 'memoria:userLogin' %}">Ingresar</a>&nbsp;
            <a style="font-size: 18px;" href="{% url 'memoria:userRegistro' %}" class="btn btn-secondary">Registro</a>
            {% endif %}
            </div>
    </nav>
    {% block content %}{% endblock %}
    <!-- Including jQuery and Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- Link to dashboard-specific JavaScript -->
    <script src="{% static 'dashboard/js/dashboard.js' %}" defer></script>
</body>
</html>

templates/dashboard/dashboard_home.html
{% extends 'dashboard/base.html' %}

{% block content %}


<div class="container mt-5">
    <div class="container">
        <h1>Estadísticas de Visitas</h1><hr>
        <canvas id="visitasChart"></canvas>
    </div>
    <script>
        var ctx = document.getElementById('visitasChart').getContext('2d');
        var visitasChart = new Chart(ctx, {
            type: 'bar',
            data: {
                labels: [{% for familiar in familiares %}'{{ familiar.nombre_familiar }} {{ familiar.apellidos_familiar }}', {% endfor %}],
                datasets: [{
                    label: 'Número de visitas',
                    data: [{% for familiar in familiares %}{{ familiar.visitas }}, {% endfor %}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(199, 199, 199, 0.2)',
                        'rgba(83, 102, 255, 0.2)',
                        'rgba(60, 179, 113, 0.2)',
                        'rgba(255, 69, 0, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(199, 199, 199, 1)',
                        'rgba(83, 102, 255, 1)',
                        'rgba(60, 179, 113, 1)',
                        'rgba(255, 69, 0, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        display: false,
                        position: 'top',
                        labels: {
                            font: {
                                size: 14,
                                weight: 'bold'
                            }
                        }
                    },
                    title: {
                        display: false,
                        text: 'Número de visitas por Familiar',
                        font: {
                            size: 33,
                            weight: 'bold'
                        }
                    },
                    datalabels: {
                        anchor: 'first',
                        align: 'end',
                        formatter: function(value, context) {
                            return value;
                        },
                        font: {
                            size: 33,
                            weight: 'bold',
                        }
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        ticks: {
                            stepSize: 1
                        }
                    }
                },
                animation: {
                    duration: 2000,
                    easing: 'easeOutBounce'
                }
            },
            plugins: [ChartDataLabels]
        });
    </script>
</div>

<div class="container mt-5">


    <h1>Bienvenido al Dashboard</h1>
    <p>Desde acá podrás gestionar tus familiares</p>
    <div class="row">
        {% for familiar in familiares %}
        <div class="col-md-3">
            <div class="card mb-3">
                <img src="{{ familiar.avatar_picture.url }}" class="card-img-top" alt="Familiar Image">
                <div class="card-body">
                    <h5 class="card-title">{{ familiar.nombre_familiar }} {{ familiar.apellidos_familiar }}</h5>
                    <p class="card-text"><b>Nacimiento:</b> {{ familiar.fecha_nacimiento }} <br> <b>Fallecimiento:</b> {{ familiar.fecha_deceso }}</p>
                    <p class="card-text"><b>Parentezco:</b> {{ familiar.parentezco }}</p>
                </div>
            </div>
        </div>

    
        {% empty %}
        <p>No familiares found.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/dashboard/dashboard_pass.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .abs-center {
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 40vh;
      }
      
    .mi_input{
        border:1px solid #red;
    }

</style>

<div class="container">
    <h1>Cambiar contraseña</h1>    

        <form method="post">
            {% csrf_token %}
            {% crispy form %}
          </form>

</div>
{% if error %}
    <p>{{ error }}</p>
{% endif %}

</div>
{% endblock %}

templates/dashboard/delete_familiar.html
{% extends 'dashboard/base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>¿Estás seguro que desea eliminar el familiar?</h2>
    <p>{{ familiar.nombre_familiar }} {{ familiar.apellidos_familiar }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'dashboard:list_familiares' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/dashboard/list_familiares.html
{% extends 'dashboard/base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Listado Familiares</h2>
    <div class="row">
        {% for familiar in familiares %}
        <div class="col-md-4">
            <div class="card mb-3">
                <a href="{% url 'carousel:carousel_home' familiar.id_familiar %}" target="_blank">
                    <img src="{{ familiar.avatar_picture.url }}" class="card-img-top" alt="Familiar Image">
                </a>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-7">
                            <h5 class="card-title">{{ familiar.nombre_familiar }} {{ familiar.apellidos_familiar }}</h5>
                            <p class="card-text"><b>Nacimiento:</b> {{ familiar.fecha_nacimiento }} <br> <b>Fallecimiento:</b> {{ familiar.fecha_deceso }}</p>
                            <p class="card-text"><b>Parentezco:</b> {{ familiar.parentezco }}</p>
                        </div>
                        <div class="col-md-5 text-center">
                            <button class="btn btn-outline-primary p-1 m-0" data-bs-toggle="modal" data-bs-target="#qrModal{{ familiar.id_familiar }}">
                                <img src="../../media/qrcodes/{{ familiar.unique_hash }}.png" class="img-fluid small-qr" alt="QR Code" style="width: 150px; height: 150px;">
                            </button>   
                        </div>
                    </div>
                    <div class="row p-1">
                        <div class="col-md-12 text-center">
                            <a href="{% url 'dashboard:update_familiar' familiar.id_familiar %}" class="btn btn-primary">Editar</a>
                            <a href="{% url 'dashboard:delete_familiar' familiar.id_familiar %}" class="btn btn-danger">Eliminar</a>
                        </div>
                    </div>                    
                </div>
            </div>
        </div>

        <div class="modal fade" id="qrModal{{ familiar.id_familiar }}" tabindex="-1" aria-labelledby="qrModalLabel{{ familiar.id_familiar }}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="qrModalLabel{{ familiar.id_familiar }}">Código QR de {{ familiar.nombre_familiar }}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-center">
                        <img src="../../media/qrcodes/{{ familiar.unique_hash }}.png" class="img-fluid" alt="QR Code">
                        <div class="mt-3">
                            <a href="whatsapp://send?text=Te invito a visitar el memorial de mi {{ familiar.parentezco }} {{ familiar.nombre_familiar }} {{ familiar.apellidos_familiar }}: https://memor-ia.cl/{{ familiar.unique_hash }}" target="_blank" class="btn btn-success">Compartir por WhatsApp</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>   
        {% empty %}
        <p>No se han encontrado familiares.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/dashboard/update_familiar.html
{% extends 'dashboard/base.html' %}

{% block content %}
<div class="container mt-5">
    <h2>Actualizar Familiar</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Actualizar</button>
    </form>
</div>
{% endblock %}

templates/dashboard/user_profile.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<style>
    .abs-center {
        display: flex;
        align-items: center;
        justify-content: center;
        min-height: 40vh;
      }
      
    .mi_input{
        border:1px solid #red;
    }

</style>

<div class="container">
    <div class="form-container">
        <h1 class="form-title">Perfil de Usuario</h1>
        <form method="post">
            {% csrf_token %}
            {% crispy form %}
            <button type="submit" class="btn btn-primary form-button">Actualizar</button>
        </form>
    </div>
</div>
{% endblock %}